name: Create PDFs

on:
  push:
    branches:
  workflow_dispatch:
  workflow_run:
    workflows: ["pages-build-deployment"]
    types:
      - completed

jobs:
  makepdfs:
    concurrency:
      group: markdown-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the pdf creation script
        uses: actions/checkout@v3.5.2
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Checkout gh-pages
        uses: actions/checkout@v3.5.2
        with:
          fetch-depth: 0
          path: pages
          ref: gh-pages
      - name: Count the commits so far
        id: commit-counter
        run: echo "::set-output name=commits::$(git -C pages rev-list --count HEAD)"
      - name: Create version
        id: version-compute
        run: echo "::set-output name=version::${{ steps.commit-counter.outputs.commits }}.$(date +"%Y.%-m%d")"
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1.146.0
        with:
          working-directory: shared-slides
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: stable
      - name: Install pdfinfo
        run: sudo apt-get install -y poppler-utils
      - name: Make the pdfs
        run: shared-slides/makepdfs.rb pages
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v6.5
      - name: Deliver the pdfs
        if: steps.branch-name.outputs.is_default == 'true'
        uses: ncipollo/release-action@v1.12.0
        with:
          allowUpdates: true
          artifacts: "*.pdf"
          replacesArtifacts: true
          repo: pss-slides
          tag: ${{ steps.version-compute.outputs.version }}
          token: ${{ secrets.DEPLOYMENT_TOKEN }}
